import sqlite3
import os

BASE_DIR = "src/files"
class DBAgent:

    def __init__(self):
        self.conn = None
        self.current_db = None

    #  PATH RESOLLUTION ( where we remove the directory root part of the path, to ensure that if goes or works on our defined workspace only)
    def _resolve_db_path(self, db_name):
        db_name = os.path.basename(db_name)
        # ensure .db extension
        if not db_name.endswith(".db"):
            db_name += ".db"

        full_path = os.path.join(BASE_DIR, "databases", db_name) # final path resolution, solving all the path incosistencies
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        return full_path
    
    # CONNECTION to the database
    def connect(self, db_name = None):
        if not db_name:
            db_name = "database.db" # fallback db, in case database name is not provided

        db_path = self._resolve_db_path(db_name) # getting the final path for the database, to ensure it is in our workspace and properly named
        # Reconnect if db closes or db changes
        if self.conn is None or self.current_db != db_path:
            if self.conn:
                self.conn.close() # terminates the previous connection 

            self.conn = sqlite3.connect(db_path) #connect to the new database, if it's different
            self.conn.row_factory = sqlite3.Row # return rows as dictionaries for easier access, making it more readable and maintainable
            self.current_db = db_path # for resusing the existing connection, if database is same 

            print(f"[DB CONNECTED] → {db_path}")

    # SQL CLEANING (removing formatting, like md or others, to ensure query(sql) is clean and ready for execution)
    def _clean_sql(self, query):
        return query.strip().replace("```sql", "").replace("```", "").strip()
    
    # MAIN ENTRY (it's how, main file (orchestrator) will call the agent to perform task)
    def handle_task(self, step, query, client, model):
        action = step.get("action")
        args = step.get("args", {})
        
        if action != "execute_sql":
            return {
                "success": False,
                "error": f"Invalid action: {action}"
            }
        sql_query = args.get("query") or args.get("sql")  # support both 'query' and 'sql' keys
        db_name = args.get("db_name") or args.get("database") # flexible input handling, in case llm generate different name for same parameter

        if not sql_query: # if no sql query is generated by the llm , and is being passed on here
            return {
                "success": False,
                "error": "Missing SQL query"
            }
        
        self.connect(db_name) # if everythin is good, it ensures the connection to the database
        return self.execute_sql(sql_query) # finally it executes the sql query, and returns the result or error if any occurs during execution

    # SQL EXECUTION (run sql query on the connected database, and return the result)
    def execute_sql(self, query):
        try:
            if not self.conn:
                return {"success": False, "error": "No DB connection"}
            query = self._clean_sql(query) # removing any formatting, for safer execution
            cursor = self.conn.cursor() # cursor is the tool for executing sql command and queries, acting as an interface for running commands
            # Support multiple SQL statements, incase more than one query is generated, where user want multiple operation in single turn
            statements = [ q.strip() for q in query.split(";") if q.strip() ] # it creates a list of valid sql commands, separated by ';'
            last_result = None
            
            for stmt in statements: # loops through each sql command, and executing them one by one
                cursor.execute(stmt)
                stmt_lower = stmt.lower()

                # SELECT queries
                if stmt_lower.startswith(("select", "pragma", "with")): # these are the main retrieval queries which retuurn data
                    rows = cursor.fetchall() # retrieves all the matching rows
                    last_result = [dict(row) for row in rows] # list of the response from the database, storing each row as dictionary for better readability and access, where column name is the key
                # Other queries ( INSERT,UPDATE OR DELETE, command that changes' database state, mainly)
                else:
                    self.conn.commit() # commits the change to the database, making it permanent
                    last_result = {"message": "Command executed"}
            return {
                "success": True,
                "result": last_result,
                "rows": len(last_result) if isinstance(last_result, list) else 0
            }

        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }